version: '3.9'

services:
  web-api:
    container_name: web-api
    image: web-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTP_PORTS=8081
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - items.database

  items.database:
    container_name: items.database
    image: postgres:16
    volumes:
      - ./.containers/items-db:/var/lib/postgresql/data
    ports:
      - 5433:5432

  nti.client:
    container_name: nti.client
    image: nti.client
    build: 
      context: ./NTI.Client
      args:
        - VITE_REACT_API_URL=http://localhost:8081/api
    ports:
      - 3000:3000
    depends_on:
      - web-api
